#ifndef PROCESSING_OUTPUT_COLOR_LIST
#   error Including OutputColorList.h, did you intend to include OutputColor.h?
#endif

PROCESS_OUTPUT_COLOR(Disabled)

// Core:
PROCESS_OUTPUT_COLOR(RNG)
PROCESS_OUTPUT_COLOR(GBufferMatIdx)
PROCESS_OUTPUT_COLOR(GBufferNormalsUnorm)
PROCESS_OUTPUT_COLOR(GBufferNormalsSnorm)
PROCESS_OUTPUT_COLOR(GBufferDepth)
PROCESS_OUTPUT_COLOR(GBufferUv)
PROCESS_OUTPUT_COLOR(GBufferMv)

// GetHitInfo:
PROCESS_OUTPUT_COLOR(InstanceIdx)
PROCESS_OUTPUT_COLOR(MaterialIdx)
PROCESS_OUTPUT_COLOR(Barycentrics)
PROCESS_OUTPUT_COLOR(Normals)
PROCESS_OUTPUT_COLOR(NormalShadedFF)
PROCESS_OUTPUT_COLOR(NormalGeometric)
PROCESS_OUTPUT_COLOR(NormalGeometricFF)
PROCESS_OUTPUT_COLOR(Tangent)
PROCESS_OUTPUT_COLOR(Bitangent)
PROCESS_OUTPUT_COLOR(UV)

// Textures:
PROCESS_OUTPUT_COLOR(TexAlbedo)
PROCESS_OUTPUT_COLOR(TexNormal)
PROCESS_OUTPUT_COLOR(TexEmissive)
PROCESS_OUTPUT_COLOR(TexRoughness)
PROCESS_OUTPUT_COLOR(TexMetallic)

// Material:
PROCESS_OUTPUT_COLOR(Albedo)
PROCESS_OUTPUT_COLOR(Opacity)
PROCESS_OUTPUT_COLOR(EmissiveStrength)
PROCESS_OUTPUT_COLOR(EmissiveColor)
PROCESS_OUTPUT_COLOR(Emission)
PROCESS_OUTPUT_COLOR(TransmissionFactor)
PROCESS_OUTPUT_COLOR(TransmissionColor)
PROCESS_OUTPUT_COLOR(Roughness)
PROCESS_OUTPUT_COLOR(Metallic)
PROCESS_OUTPUT_COLOR(SpecularFactor)
PROCESS_OUTPUT_COLOR(AnisoStrength)
PROCESS_OUTPUT_COLOR(IorN)

// BSDF:
PROCESS_OUTPUT_COLOR(H_s)
PROCESS_OUTPUT_COLOR(H_w)
PROCESS_OUTPUT_COLOR(L_s)
PROCESS_OUTPUT_COLOR(L_w)
PROCESS_OUTPUT_COLOR(Alpha)
PROCESS_OUTPUT_COLOR(D)
PROCESS_OUTPUT_COLOR(G)
PROCESS_OUTPUT_COLOR(F)
PROCESS_OUTPUT_COLOR(f)
PROCESS_OUTPUT_COLOR(PDF)
PROCESS_OUTPUT_COLOR(SpecProb)
PROCESS_OUTPUT_COLOR(ReflectProb)

// NEE:
PROCESS_OUTPUT_COLOR(NEE_L_w)
PROCESS_OUTPUT_COLOR(NEE_PDF)
PROCESS_OUTPUT_COLOR(NEE_Occluded)
PROCESS_OUTPUT_COLOR(NEE_Le)
PROCESS_OUTPUT_COLOR(NEE_MIS_Weight)