#ifndef H_FLAGS_METHODS_HLSL_H
#define H_FLAGS_METHODS_HLSL_H

#ifdef __cplusplus
#   error HLSL only
#endif

#include "PathTracing/Flags/Flags.h"

#   ifndef FEATURE_FLAGS
#       define FEATURE_FLAGS 0
#   endif

#   ifndef DEBUG_FLAGS
#       define DEBUG_FLAGS 0
#   endif

#define FEATURE_ENABLED(flag) (FEATURE_FLAGS & FEATURE_FLAG_VALUE_##flag)
#define DEBUG_ENABLED(flag)   (DEBUG_FLAGS & DEBUG_FLAG_VALUE_##flag)

// Combined Flags

#define FEATURES_ENABLED_ANY2(_1, _2)             FEATURE_ENABLED(_1) || FEATURE_ENABLED(_2)
#define FEATURES_ENABLED_ANY3(_1, _2, _3)         FEATURE_ENABLED(_1) || FEATURE_ENABLED(_2) || FEATURE_ENABLED(_3)
#define FEATURES_ENABLED_ANY4(_1, _2, _3, _4)     FEATURE_ENABLED(_1) || FEATURE_ENABLED(_2) || FEATURE_ENABLED(_3) || FEATURE_ENABLED(_4)

#define DEBUGS_ENABLED_ANY2(_1, _2)               DEBUG_ENABLED(_1) || DEBUG_ENABLED(_2)
#define DEBUGS_ENABLED_ANY3(_1, _2, _3)           DEBUG_ENABLED(_1) || DEBUG_ENABLED(_2) || DEBUG_ENABLED(_3)
#define DEBUGS_ENABLED_ANY4(_1, _2, _3, _4)       DEBUG_ENABLED(_1) || DEBUG_ENABLED(_2) || DEBUG_ENABLED(_3) || DEBUG_ENABLED(_4)

#define FEATURES_ENABLED_ALL2(_1, _2)             FEATURE_ENABLED(_1) && FEATURE_ENABLED(_2)
#define FEATURES_ENABLED_ALL3(_1, _2, _3)         FEATURE_ENABLED(_1) && FEATURE_ENABLED(_2) && FEATURE_ENABLED(_3)
#define FEATURES_ENABLED_ALL4(_1, _2, _3, _4)     FEATURE_ENABLED(_1) && FEATURE_ENABLED(_2) && FEATURE_ENABLED(_3) && FEATURE_ENABLED(_4)

#define DEBUGS_ENABLED_ALL2(_1, _2)               DEBUG_ENABLED(_1) && DEBUG_ENABLED(_2)
#define DEBUGS_ENABLED_ALL3(_1, _2, _3)           DEBUG_ENABLED(_1) && DEBUG_ENABLED(_2) && DEBUG_ENABLED(_3)
#define DEBUGS_ENABLED_ALL4(_1, _2, _3, _4)       DEBUG_ENABLED(_1) && DEBUG_ENABLED(_2) && DEBUG_ENABLED(_3) && DEBUG_ENABLED(_4)

#endif