
file(GLOB_RECURSE PROJECT_SOURCES CONFIGURE_DEPENDS "Source/Client/*.cpp")

file(GLOB_RECURSE PROJECT_HEADERS CONFIGURE_DEPENDS "Headers/Client/*.h")

set(IS_DEBUG FALSE)

if(CMAKE_BUILD_TYPE STREQUAL "Debug")
    set(IS_DEBUG TRUE)
endif()

if(CMAKE_CONFIGURATION_TYPES)
    list(FIND CMAKE_CONFIGURATION_TYPES "Debug" HAS_DEBUG)
    if(NOT HAS_DEBUG EQUAL -1)
        set(IS_DEBUG TRUE)
    endif()
endif()

if(NOT IS_DEBUG)
    list(FILTER PROJECT_SOURCES EXCLUDE REGEX ".*/Source/Client/Debug/.*")
    list(FILTER PROJECT_HEADERS EXCLUDE REGEX ".*/Headers/Client/Debug/.*")
endif()