# Source files
set(PROJECT_SOURCES
        src/client/MathUtils.cpp
        src/client/HWI/BLAS.cpp
        src/client/HWI/D12Resource.cpp
        src/client/HWI/D3D.cpp
        src/client/HWI/Heap.cpp
        src/client/HWI/Material.cpp
        src/client/HWI/Model.cpp
        src/client/HWI/RootSig.cpp
        src/client/HWI/Shader.cpp
        src/client/HWI/Texture.cpp
        src/client/HWI/TLAS.cpp
        src/client/Render/Camera.cpp
        src/client/Render/CameraController.cpp
        src/client/Render/DeferredContext.cpp
        src/client/Render/DenoisingManager.cpp
        src/client/Render/EnvMap.cpp
        src/client/Render/Object.cpp
        src/client/Render/PathTracingContext.cpp
        src/client/Render/RasterContext.cpp
        src/client/Render/Scene.cpp
        src/client/Render/Skybox.cpp
        src/client/Render/TextureRTV.cpp
        src/client/Render/Transform.cpp
        src/client/System/App.cpp
        src/client/System/CherryPip.cpp
        src/client/System/Config.cpp
        src/client/System/Engine.cpp
        src/client/System/Engine_GUI.cpp
        src/client/System/FileHelper.cpp
        src/client/System/Gui.cpp
        src/client/System/HighResolutionClock.cpp
        src/client/System/ImGuiUtils.cpp
        src/client/System/Input.cpp
        src/client/System/ModelLoaderGLTF.cpp
        src/client/System/ResourceSharer.cpp
        src/client/System/TextureLoader.cpp
        src/client/System/Win32App.cpp
)

# Header files
set(PROJECT_HEADERS
        Headers/client/Helper.h
        Headers/client/MathUtils.h
        Headers/client/HWI/BLAS.h
        Headers/client/HWI/D12Resource.h
        Headers/client/HWI/D3D.h
        Headers/client/HWI/Heap.h
        Headers/client/HWI/Material.h
        Headers/client/HWI/Model.h
        Headers/client/HWI/RootSig.h
        Headers/client/HWI/Shader.h
        Headers/client/HWI/Texture.h
        Headers/client/HWI/TLAS.h
        Headers/client/Render/Camera.h
        Headers/client/Render/CameraController.h
        Headers/client/Render/DeferredContext.h
        Headers/client/Render/DenoisingManager.h
        Headers/client/Render/EnvMap.h
        Headers/client/Render/Object.h
        Headers/client/Render/PathTracingContext.h
        Headers/client/Render/RasterContext.h
        Headers/client/Render/Scene.h
        Headers/client/Render/Skybox.h
        Headers/client/Render/TextureRTV.h
        Headers/client/Render/Transform.h
        Headers/client/System/App.h
        Headers/client/System/CherryPip.h
        Headers/client/System/Config.h
        Headers/client/System/FileHelper.h
        Headers/client/System/Gui.h
        Headers/client/System/HighResolutionClock.h
        Headers/client/System/ImGuiUtils.h
        Headers/client/System/Input.h
        Headers/client/System/Keycodes.h
        Headers/client/System/ResourceSharer.h
        Headers/client/System/TextureLoader.h
        Headers/client/System/Win32App.h
)

if(CMAKE_BUILD_TYPE STREQUAL "Debug" OR CMAKE_CONFIGURATION_TYPES MATCHES "Debug")
    set(PROJECT_SOURCES
            ${PROJECT_SOURCES}
            src/client/Debug/DebugLine.cpp
            src/client/Debug/GPUEventScoped.cpp
            src/client/Debug/HotReloader.cpp
            src/client/Debug/PathVisualizer.cpp
            src/client/Debug/PythonExecutor.cpp
            src/client/Debug/Profiler.cpp
            src/client/Debug/ReadbackBuffer.cpp
            src/client/Debug/RmseTester.cpp
    )
    set(PROJECT_HEADERS
            ${PROJECT_HEADERS}
            Headers/client/Debug/DebugOutputRedirector.h
            Headers/client/Debug/DebugLine.h
            Headers/client/Debug/GPUEventScoped.h
            Headers/client/Debug/HotReloader.h
            Headers/client/Debug/PathVisualizer.h
            Headers/client/Debug/PythonExecutor.h
            Headers/client/Debug/Profiler.h
            Headers/client/Debug/ReadbackBuffer.h
            Headers/client/Debug/RmseTester.h
    )
endif()