
file(GLOB_RECURSE PROJECT_SOURCES "Source/Client/*.cpp")

file(GLOB_RECURSE PROJECT_HEADERS "Headers/Client/*.h")

set(IS_DEBUG CMAKE_BUILD_TYPE STREQUAL "Debug" OR CMAKE_CONFIGURATION_TYPES MATCHES "Debug")

if(NOT IS_DEBUG)
    list(FILTER PROJECT_SOURCES EXCLUDE REGEX ".*/Source/Client/Debug/.*")
    list(FILTER PROJECT_HEADERS EXCLUDE REGEX ".*/Headers/Client/Debug/.*")
endif()